version: "3.3"
services:
  back:
    container_name: back
    build: back/.
    ports:
      - "4200:4200"
    depends_on:
      - db
    env_file:
      - back/.env.prod
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - examplenetwork

  front:
    container_name: front
    build: front/.
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - examplenetwork
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

networks:
  examplenetwork:
    driver: bridge

volumes:
  postgresql:
  postgresql_data:
